#!/bin/bash -p
#
# p4d start-stop script
#
### BEGIN INIT INFO
# Provides:          p4d
# Required-Start:    hostname $local_fs $network $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Deamon to capture data of the P4 pellet heating
# Description:       Deamon to capture data of the P4 pellet heating
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=p4d
DESC="Deamon to capture data of the P4 pellet heating"

DAEMON=/usr/local/bin/runp4d
BIN=/usr/local/bin/p4d
PIDFILE=/var/run/p4d.pid

test -x $DAEMON || exit 0

get_status()
{
    if start-stop-daemon --start --startas $DAEMON --test \
        --name $(basename $DAEMON) --pidfile $PIDFILE >/dev/null
    then
        echo " - is not running."
        exit 3
    else
        echo " - is running."
        exit 0
    fi
}

startp4d()
{
   # only start if there is no other instance running
   if start-stop-daemon --start --startas $DAEMON --test \
       --name $(basename $DAEMON) --pidfile $PIDFILE >/dev/null
   then
       export LC_TIME="de_DE.UTF-8"
       export TZ=CET
       ulimit -c unlimited
       # echo "/var/log/cores/core.%e" > /proc/sys/kernel/core_pattern

       start-stop-daemon --start --quiet --startas $DAEMON --background \
           --name $(basename $DAEMON) --pidfile $PIDFILE --make-pidfile -- \
           -n 
   else
       echo -n " - seems to be running already"
   fi
}

stopp4d()
{
    if start-stop-daemon --stop --retry 30 \
        --name $(basename $DAEMON) --pidfile $PIDFILE >/dev/null
    then
        start-stop-daemon --stop --retry 30 --oknodo --exec $BIN >/dev/null
        rm -f $PIDFILE
    else
        echo -n " - seems not to be running"
    fi
}

case "$1" in
    start)
        echo -n "Starting $DESC: $NAME"
        startp4d
        echo "."
        ;;
    stop)
        echo -n "Stopping $DESC: $NAME"
        stopp4d
        echo "."
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: $NAME"
        stopp4d
        sleep 1
        startp4d
        echo "."
        ;;
    status)
        echo -n "Getting status of $DESC: $NAME"
        get_status
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
