#! /bin/bash

# Parameters:
#   1 - command {init|start|stop|status|toggle}
#   2 - address
#   3 - answer topic
#   4 - service

# Responce:
#   Responce in JSON Format, expected elements are_
#     type      - always SC                       (madatory / element type string)
#     address   - mainly taken from parameter 2   (madatory / element type integer)
#     kind      - kind sensor {status|value|text} (madatory / element type string)
#     value     -                                 (optional one of state, value or text must set / element type real)
#     state     -                                 (optional one of state, value or text must set / element type boolean)
#     text      -                                 (optional one of state, value or text must set / element type string)
#     unit      -                                 (optional / element type string)

SYSTEMCTL=systemctl

# special for chroot setup on odroid

if [[ -f /storage/bin/systemctl.sh ]]; then
   SYSTEMCTL=/storage/bin/systemctl.sh
fi

COMMAND="$1"
ADDRESS="$2"
MQTTURL="$3"
SERVICE="$4"

export HOME=/var/lib/homectld

case "$COMMAND" in
    start)
        ${SYSTEMCTL} start --quiet ${SERVICE}
        ;;

    stop)
        ${SYSTEMCTL} stop --quiet ${SERVICE}
        ;;

    restart)
        ${SYSTEMCTL} restart --quiet ${SERVICE}
        ;;

    toggle)
        ${SYSTEMCTL} is-active --quiet ${SERVICE}
        if [ $? == 0 ]; then
            ${SYSTEMCTL} stop --quiet ${SERVICE}
        else
            ${SYSTEMCTL} start --quiet ${SERVICE}
        fi
        ;;

    status)
        ;;

    init)
        ;;

    *)
       echo "Usage: {start|stop|status|toggle|init}"
       ;;

esac

${SYSTEMCTL} is-active --quiet ${SERVICE}
RETVAL="$?"

if [ ${RETVAL} == 0 ]; then
   STATE="true"
else
   STATE="false"
fi

if [ "${COMMAND}" != "init" ]; then
   mosquitto_pub --quiet -L ${MQTTURL} -m "{ \"type\":\"SC\",\"address\":${ADDRESS},\"kind\":\"status\",\"state\":${STATE} }"
fi

echo -n "{ \"type\":\"SC\",\"address\":${ADDRESS},\"kind\":\"status\",\"value\":${STATE} }"

exit ${RETVAL}
