#!/bin/bash 

echo "---------------------"
echo "-- Drop all tables --"
echo "---------------------"
echo -n "Are you sure? [y/N] " 

read -n 1 c

echo ""

if [ "${c}" = "y" ]; then 
   
   mysql -u p4 -pp4 -Dp4 -e 'drop table config;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table errors;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table jobs;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table schemaconf;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table sensoralert;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table valuefacts;'
   mysql -u p4 -pp4 -Dp4 -e 'drop table menu;'

   echo "Tables droped!"
fi

echo "---------------------"
echo "-- Drop samples --"
echo "---------------------"
echo -n "Are you sure? [y/N] " 

read -n 1 c

echo ""

if [ "${c}" = "y" ]; then

   mysql -u p4 -pp4 -Dp4 -e 'drop table samples;'

fi
